TEAM_TO_TEAM_ABBR = {
        'ATLANTA HAWKS': 'ATL',
        'BOSTON CELTICS': 'BOS',
        'BROOKLYN NETS': 'BRK',
        'CHICAGO BULLS': 'CHI',
        'CHARLOTTE HORNETS': 'CHO',
        'CLEVELAND CAVALIERS': 'CLE',
        'DALLAS MAVERICKS': 'DAL',
        'DENVER NUGGETS': 'DEN',
        'DETROIT PISTONS': 'DET',
        'GOLDEN STATE WARRIORS': 'GSW',
        'HOUSTON ROCKETS': 'HOU',
        'INDIANA PACERS': 'IND',
        'LOS ANGELES CLIPPERS': 'LAC',
        'LOS ANGELES LAKERS': 'LAL',
        'MEMPHIS GRIZZLIES': 'MEM',
        'MIAMI HEAT': 'MIA',
        'MILWAUKEE BUCKS': 'MIL',
        'MINNESOTA TIMBERWOLVES': 'MIN',
        'NEW ORLEANS PELICANS': 'NOP',
        'NEW YORK KNICKS': 'NYK',
        'OKLAHOMA CITY THUNDER': 'OKC',
        'ORLANDO MAGIC': 'ORL',
        'PHILADELPHIA 76ERS': 'PHI',
        'PHOENIX SUNS': 'PHO',
        'PORTLAND TRAIL BLAZERS': 'POR',
        'SACRAMENTO KINGS': 'SAC',
        'SAN ANTONIO SPURS': 'SAS',
        'TORONTO RAPTORS': 'TOR',
        'UTAH JAZZ': 'UTA',
        'WASHINGTON WIZARDS': 'WAS',
}


TEAM_ABV_DICTIONARY = [
        {'team': 'ATLANTA HAWKS', 'abv': 'ATL'},
        {'team': 'BOSTON CELTICS', 'abv': 'BOS'},
        {'team': 'BROOKLYN NETS', 'abv': 'BRK'},
        {'team': 'CHICAGO BULLS', 'abv': 'CHI'},
        {'team': 'CHARLOTTE HORNETS', 'abv': 'CHO'},
        {'team': 'CLEVELAND CAVALIERS', 'abv': 'CLE'},
        {'team': 'DALLAS MAVERICKS', 'abv': 'DAL'},
        {'team': 'DENVER NUGGETS', 'abv': 'DEN'},
        {'team': 'DETROIT PISTONS', 'abv': 'DET'},
        {'team': 'GOLDEN STATE WARRIORS', 'abv': 'GSW'},
        {'team': 'HOUSTON ROCKETS', 'abv': 'HOU'},
        {'team': 'INDIANA PACERS', 'abv': 'IND'},
        {'team': 'LOS ANGELES CLIPPERS', 'abv': 'LAC'},
        {'team': 'LOS ANGELES LAKERS', 'abv': 'LAL'},
        {'team': 'MEMPHIS GRIZZLIES', 'abv': 'MEM'},
        {'team': 'MIAMI HEAT', 'abv': 'MIA'},
        {'team': 'MILWAUKEE BUCKS', 'abv': 'MIL'},
        {'team': 'MINNESOTA TIMBERWOLVES', 'abv': 'MIN'},
        {'team': 'NEW ORLEANS PELICANS', 'abv': 'NOP'},
        {'team': 'NEW YORK KNICKS', 'abv': 'NYK'},
        {'team': 'OKLAHOMA CITY THUNDER', 'abv': 'OKC'},
        {'team': 'ORLANDO MAGIC', 'abv': 'ORL'},
        {'team': 'PHILADELPHIA 76ERS', 'abv': 'PHI'},
        {'team': 'PHOENIX SUNS', 'abv': 'PHO'},
        {'team': 'PORTLAND TRAIL BLAZERS', 'abv': 'POR'},
        {'team': 'SACRAMENTO KINGS', 'abv': 'SAC'},
        {'team': 'SAN ANTONIO SPURS', 'abv': 'SAS'},
        {'team': 'TORONTO RAPTORS', 'abv': 'TOR'},
        {'team': 'UTAH JAZZ', 'abv': 'UTA'},
        {'team': 'WASHINGTON WIZARDS', 'abv': 'WAS'}
]

